default: &default
development:
  adapter: postgresql
  encoding: unicode
  database: f9_development
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: f9
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: f9_test
  pool: 5
  username: f9
  password:
    